### ISSUE TITLE
Missing `arc_processed.csv` in `source/arc/` directory

### ISSUE THREAD

**Issue by bebr2** [feyzaakyurek/dune#2]
Hello,

Thanks for your excellent work! I've been reviewing the `ARC` class in the `EditDataset` module and noticed a reference to the file `arc_processed.csv` within the `source/arc/` directory. However, it appears that this file is missing. I was also unable to locate some files for other datasets.

Could you please clarify if there's an issue with the file locations or if they're supposed to be generated during the dataset processing? Any guidance on how to resolve this and ensure all necessary files are present would be greatly appreciated.

Thank you!

**Comment by feyzaakyurek** [comment]
Hi Wang,

This [line](https://github.com/feyzaakyurek/dune/blob/master/dataset.py#L159) should've been optional for eval since we're loading test_inputs [here](https://github.com/feyzaakyurek/dune/blob/master/eval.py#L135). I fixed that--but also uploaded those files mentioned in the dataset.py to the drive link [here](https://drive.google.com/drive/folders/1hDpD97Urt9dLXdFSGfigKCzLshhztn5I?usp=drive_link).

Thanks for pointing this out!

**Comment by bebr2** [comment]
Thank you for your response and for uploading the missing files. I have checked the drive link you provided and was able to access the files.

Once again, thank you for your assistance!
